#!/bin/bash
# Count lines of code per .go file, with optional folder exclusions.
# Usage: ./loc.sh [exclude_dir ...]
# Example: ./loc.sh proto vendor notebooks

FIND_ARGS=(. -name '*.go')
for dir in "$@"; do
    FIND_ARGS+=(-not -path "*/${dir}/*")
done

find "${FIND_ARGS[@]}" | xargs wc -l | sort -n
